POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Bob",
    "number": "123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Bob"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123456"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "123456"
}